name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          echo ${{ secrets.SECRET_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker pull ghcr.io/$GITHUB_REPOSITORY:latest
          docker build . --tag ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA --cache-from ghcr.io/$GITHUB_REPOSITORY:latest
          docker push ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA

      - name: Deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image -n docs --record deployment/capwell-ui capwell-ui=ghcr.io/$GITHUB_REPOSITORY:$GITHUB_SHA
